In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('ACS_14_1YR_S2406_with_ann.csv')
df.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_EST_VC01,HC01_MOE_VC01,HC02_EST_VC01,HC02_MOE_VC01,HC03_EST_VC01,HC03_MOE_VC01,HC04_EST_VC01,...,HC02_EST_VC09,HC02_MOE_VC09,HC03_EST_VC09,HC03_MOE_VC09,HC04_EST_VC09,HC04_MOE_VC09,HC05_EST_VC09,HC05_MOE_VC09,HC06_EST_VC09,HC06_MOE_VC09
0,Id,Id2,Geography,Total; Estimate; Civilian employed population ...,Total; Margin of Error; Civilian employed popu...,Employee of private company workers; Estimate;...,Employee of private company workers; Margin of...,Self-employed in own incorporated business wor...,Self-employed in own incorporated business wor...,Private not-for-profit wage and salary workers...,...,Employee of private company workers; Estimate;...,Employee of private company workers; Margin of...,Self-employed in own incorporated business wor...,Self-employed in own incorporated business wor...,Private not-for-profit wage and salary workers...,Private not-for-profit wage and salary workers...,"Local, state, and federal government workers; ...","Local, state, and federal government workers; ...",Self-employed in own not incorporated business...,Self-employed in own not incorporated business...
1,0400000US01,01,Alabama,2030482,13376,69.0,0.6,2.7,0.2,6.9,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
2,0400000US02,02,Alaska,352531,5376,54.4,1.4,3.7,0.5,10.0,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
3,0400000US04,04,Arizona,2866629,19029,69.8,0.6,3.4,0.2,6.4,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
4,0400000US05,05,Arkansas,1269092,12369,67.4,0.8,3.0,0.2,7.1,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [16]:
df.columns

Index(['GEO.id', 'GEO.id2', 'GEO.display-label', 'HC01_EST_VC01',
       'HC01_MOE_VC01', 'HC02_EST_VC01', 'HC02_MOE_VC01', 'HC03_EST_VC01',
       'HC03_MOE_VC01', 'HC04_EST_VC01', 'HC04_MOE_VC01', 'HC05_EST_VC01',
       'HC05_MOE_VC01', 'HC06_EST_VC01', 'HC06_MOE_VC01', 'HC01_EST_VC02',
       'HC01_MOE_VC02', 'HC02_EST_VC02', 'HC02_MOE_VC02', 'HC03_EST_VC02',
       'HC03_MOE_VC02', 'HC04_EST_VC02', 'HC04_MOE_VC02', 'HC05_EST_VC02',
       'HC05_MOE_VC02', 'HC06_EST_VC02', 'HC06_MOE_VC02', 'HC01_EST_VC03',
       'HC01_MOE_VC03', 'HC02_EST_VC03', 'HC02_MOE_VC03', 'HC03_EST_VC03',
       'HC03_MOE_VC03', 'HC04_EST_VC03', 'HC04_MOE_VC03', 'HC05_EST_VC03',
       'HC05_MOE_VC03', 'HC06_EST_VC03', 'HC06_MOE_VC03', 'HC01_EST_VC04',
       'HC01_MOE_VC04', 'HC02_EST_VC04', 'HC02_MOE_VC04', 'HC03_EST_VC04',
       'HC03_MOE_VC04', 'HC04_EST_VC04', 'HC04_MOE_VC04', 'HC05_EST_VC04',
       'HC05_MOE_VC04', 'HC06_EST_VC04', 'HC06_MOE_VC04', 'HC01_EST_VC05',
       'HC01_MOE_VC05', 'HC02_EST_VC05', 'HC02_MOE_VC05', 'HC03_EST_VC05',
       'HC03_MOE_VC05', 'HC04_EST_VC05', 'HC04_MOE_VC05', 'HC05_EST_VC05',
       'HC05_MOE_VC05', 'HC06_EST_VC05', 'HC06_MOE_VC05', 'HC01_EST_VC06',
       'HC01_MOE_VC06', 'HC02_EST_VC06', 'HC02_MOE_VC06', 'HC03_EST_VC06',
       'HC03_MOE_VC06', 'HC04_EST_VC06', 'HC04_MOE_VC06', 'HC05_EST_VC06',
       'HC05_MOE_VC06', 'HC06_EST_VC06', 'HC06_MOE_VC06', 'HC01_EST_VC09',
       'HC01_MOE_VC09', 'HC02_EST_VC09', 'HC02_MOE_VC09', 'HC03_EST_VC09',
       'HC03_MOE_VC09', 'HC04_EST_VC09', 'HC04_MOE_VC09', 'HC05_EST_VC09',
       'HC05_MOE_VC09', 'HC06_EST_VC09', 'HC06_MOE_VC09'],
      dtype='object')

In [17]:
cols = [c for c in df.columns if c.lower()[5:8] != 'moe']
cols

['GEO.id',
 'GEO.id2',
 'GEO.display-label',
 'HC01_EST_VC01',
 'HC02_EST_VC01',
 'HC03_EST_VC01',
 'HC04_EST_VC01',
 'HC05_EST_VC01',
 'HC06_EST_VC01',
 'HC01_EST_VC02',
 'HC02_EST_VC02',
 'HC03_EST_VC02',
 'HC04_EST_VC02',
 'HC05_EST_VC02',
 'HC06_EST_VC02',
 'HC01_EST_VC03',
 'HC02_EST_VC03',
 'HC03_EST_VC03',
 'HC04_EST_VC03',
 'HC05_EST_VC03',
 'HC06_EST_VC03',
 'HC01_EST_VC04',
 'HC02_EST_VC04',
 'HC03_EST_VC04',
 'HC04_EST_VC04',
 'HC05_EST_VC04',
 'HC06_EST_VC04',
 'HC01_EST_VC05',
 'HC02_EST_VC05',
 'HC03_EST_VC05',
 'HC04_EST_VC05',
 'HC05_EST_VC05',
 'HC06_EST_VC05',
 'HC01_EST_VC06',
 'HC02_EST_VC06',
 'HC03_EST_VC06',
 'HC04_EST_VC06',
 'HC05_EST_VC06',
 'HC06_EST_VC06',
 'HC01_EST_VC09',
 'HC02_EST_VC09',
 'HC03_EST_VC09',
 'HC04_EST_VC09',
 'HC05_EST_VC09',
 'HC06_EST_VC09']

In [18]:
df = df[cols]

In [21]:
df.head(1).T.to_csv('columns.csv')

In [25]:
df.describe()

,GEO.id,GEO.id2,GEO.display-label,HC01_EST_VC01,HC02_EST_VC01,HC03_EST_VC01,HC04_EST_VC01,HC05_EST_VC01,HC06_EST_VC01,HC01_EST_VC02,...,HC03_EST_VC06,HC04_EST_VC06,HC05_EST_VC06,HC06_EST_VC06,HC01_EST_VC09,HC02_EST_VC09,HC03_EST_VC09,HC04_EST_VC09,HC05_EST_VC09,HC06_EST_VC09
count,53,53,53,53,53,53,53,53,53,53,...,53,53,53,53,53,53,53,53,53,53
unique,53,53,53,53,43,24,42,45,36,53,...,21,24,42,31,38,2,2,2,2,2
top,0400000US23,48,California,1269092,70.0,3.4,7.8,12.0,5.7,1733574,...,1.4,2.9,3.6,4.7,11.6,(X),(X),(X),(X),(X)
freq,1,1,1,1,3,7,3,4,4,1,...,6,5,3,5,4,52,52,52,52,52

In [26]:
df.to_csv('filtered.csv')

In [29]:
cols = ['GEO.display-label','HC01_EST_VC01','HC01_EST_VC02','HC01_EST_VC03','HC01_EST_VC04','HC01_EST_VC05','HC01_EST_VC06']

In [31]:
df[cols].to_csv('totals.csv')